// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
  
    

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
        
    }
    
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkpLpyB2YM6Och6fkQEZsbtkjEbOa7AjA',
    appId: '1:943794387340:web:36409edea26a6d89077ea9',
    messagingSenderId: '943794387340',
    projectId: 'nanny-cares',
    authDomain: 'nanny-cares.firebaseapp.com',
    storageBucket: 'nanny-cares.firebasestorage.app',
    measurementId: 'G-VN48MP877H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCnUutysCt6jOIOU74g_HwFpOLLWL4ENM',
    appId: '1:943794387340:android:8d83fc62048e2c78077ea9',
    messagingSenderId: '943794387340',
    projectId: 'nanny-cares',
    storageBucket: 'nanny-cares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoIdbDqV2HiSZEAvYT8MxR1cK9-r_dgo',
    appId: '1:943794387340:ios:a89bba59db5dbfc4077ea9',
    messagingSenderId: '943794387340',
    projectId: 'nanny-cares',
    storageBucket: 'nanny-cares.firebasestorage.app',
    iosBundleId: 'com.example.nannycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpoIdbDqV2HiSZEAvYT8MxR1cK9-r_dgo',
    appId: '1:943794387340:ios:a89bba59db5dbfc4077ea9',
    messagingSenderId: '943794387340',
    projectId: 'nanny-cares',
    storageBucket: 'nanny-cares.firebasestorage.app',
    iosBundleId: 'com.example.nannycare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkpLpyB2YM6Och6fkQEZsbtkjEbOa7AjA',
    appId: '1:943794387340:web:8d41497508fa02c3077ea9',
    messagingSenderId: '943794387340',
    projectId: 'nanny-cares',
    authDomain: 'nanny-cares.firebaseapp.com',
    storageBucket: 'nanny-cares.firebasestorage.app',
    measurementId: 'G-PYV2QDT6MC',
  );
}
