// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNiT4Xuv9vlUbkWA7CT3X5Izok6IVRMbg',
    appId: '1:1083795154235:web:452e1a4e42cac847b5431e',
    messagingSenderId: '1083795154235',
    projectId: 'flutterdb-e4d59',
    authDomain: 'flutterdb-e4d59.firebaseapp.com',
    storageBucket: 'flutterdb-e4d59.firebasestorage.app',
    measurementId: 'G-Z8THNLCPJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpzPLZjIjMDL8ByMkWRkHTMmKo5D0w_Q',
    appId: '1:1083795154235:android:ead01903fd4dfbf5b5431e',
    messagingSenderId: '1083795154235',
    projectId: 'flutterdb-e4d59',
    storageBucket: 'flutterdb-e4d59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD24Dse5YgYN6DZJ5wytZBT6Y1zOiv6qig',
    appId: '1:1083795154235:ios:3e43d37d021bde90b5431e',
    messagingSenderId: '1083795154235',
    projectId: 'flutterdb-e4d59',
    storageBucket: 'flutterdb-e4d59.firebasestorage.app',
    iosBundleId: 'com.example.module24LabExercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD24Dse5YgYN6DZJ5wytZBT6Y1zOiv6qig',
    appId: '1:1083795154235:ios:3e43d37d021bde90b5431e',
    messagingSenderId: '1083795154235',
    projectId: 'flutterdb-e4d59',
    storageBucket: 'flutterdb-e4d59.firebasestorage.app',
    iosBundleId: 'com.example.module24LabExercise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNiT4Xuv9vlUbkWA7CT3X5Izok6IVRMbg',
    appId: '1:1083795154235:web:bd873d7beb1ce5f9b5431e',
    messagingSenderId: '1083795154235',
    projectId: 'flutterdb-e4d59',
    authDomain: 'flutterdb-e4d59.firebaseapp.com',
    storageBucket: 'flutterdb-e4d59.firebasestorage.app',
    measurementId: 'G-08EQ48LDK4',
  );
}
